<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-NexaCommerce.ReportScheduler-094dac6b-2522-4153-9a4f-86e1ad45ab61</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
    <PackageReference Include="Quartz" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared-kernel\NexaCommerce.SharedKernel\NexaCommerce.SharedKernel.csproj" />
    <ProjectReference Include="..\NexaCommerce.ReportScheduler.Data\NexaCommerce.ReportScheduler.Data.csproj" />
  </ItemGroup>

</Project>

